### ISSUE TITLE
SoftDelete - Slug generation issue

### ISSUE THREAD

**Issue by Adrion** [initbiz/oc-cumuluscore-plugin#24]
Related to https://github.com/octobercms/october/issues/4192

We may recover Validation rules on Cluster model, at least for slug and name properties. 
We should prevent slug duplication when the first one is soft deleted.

I'll try to recover validation rule and make some tests locally

**Comment by czerwonyd** [comment]
I would love to recover them.

Make tests please if this is possible and I will definitely take a closer look at them in near future.

Post me please about the progress.

Thanks :)

**Comment by Adrion** [comment]
I made a PR October side for this issue : https://github.com/octobercms/library/pull/388

What was the issue with validation rules ? 
In your TODO you only speak about email field. Can we recover the others ?

**Comment by czerwonyd** [comment]
As far as I remember it was something with auto assigning clusters. In the rules email was not marked as required but while auto assign it was acting like it's required.

I will leave the issue opened until I restore the rules. When I do it I will post you here.

**Comment by tomaszstrojny** [comment]
Finally managed to move this issue and it's all fixed in version 3.1.0.

In the end I've noticed that my idea wasn't compatible with the RainLab's, but I hope this will not be a problem.

Clusters and plans are permanently removed after someone decides to remove them once again. Validation rules are not perfect so if you have any ideas of how to improve them I'm open for suggestions.
